# ⚠️ En production, utiliser Kubernetes Secrets chiffrés (Sealed Secrets ou Vault)
# Ces valeurs sont encodées en base64 :
#   echo -n 'marketwatch_db'   | base64  → bWFya2V0d2F0Y2hfZGI=
#   echo -n 'marketwatch_user' | base64  → bWFya2V0d2F0Y2hfdXNlcg==
#   echo -n 'marketwatch_pass' | base64  → bWFya2V0d2F0Y2hfcGFzcw==
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: marketwatch
type: Opaque
data:
  POSTGRES_DB: bWFya2V0d2F0Y2hfZGI=
  POSTGRES_USER: bWFya2V0d2F0Y2hfdXNlcg==
  POSTGRES_PASSWORD: bWFya2V0d2F0Y2hfcGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: marketwatch
type: Opaque
data:
  # echo -n 'votre-secret-jwt-tres-long-et-securise-256bits' | base64
  JWT_SECRET: dm90cmUtc2VjcmV0LWp3dC10cmVzLWxvbmctZXQtc2VjdXJpc2UtMjU2Yml0cw==
